version: "3"
services:
  vc-notf:
    image: ghcr.io/cordx56/vc-notf:latest
    command: /bin/bash -c "sqlx migrate run && vc-notf"
    env_file:
      - .env
    restart: always
  db:
    image: postgres:14
    ports:
      - 5432:5432
    env_file:
      - .env
    restart: always
